env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: Test Secrets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Run our script with secrets
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: node index.js